### ISSUE TITLE
Complete statistics tracking

### ISSUE THREAD

**Issue by aramperes** [GlowstoneMC/Glowstone#327]
**Task description**: Right now, the statistics system for loading/saving is complete. However, only the "time played" statistic is currently tracked. Therefore, we need to complete those statistics as well.

_Anyone can feel free to contribute on a smaller or larger portion of this task as they feel. There is no absolute need to complete all of the following in one PR. Hop on the [Discord channel](https://discord.gg/TFJqhsC) to have a chat with other contributors._

_If you plan on working on this task, please feel free to let us know in the comments. If you plan on working on a larger portion of the task, please open a Work In Progress Pull Request so we can track this issue._

---

**Statistics to track**
- [x] Games quit
- [x] Time since last death
- [x] Sneak time
- [x] Distance walked
- [x] Distance crouched
- [x] Distance sprinted
- [x] Distance swum
- [ ] Distance fallen
- [x] Distance climbed
- [x] Distance flown
- [ ] Distance dove
- [ ] Distance by Minecart
- [ ] Distance by Boat
- [ ] Distance by Elytra
- [x] Jumps
- [x] Items dropped
- [x] Damage dealt
- [x] Damage taken
- [x] Number of deaths
- [x] Mob kills
- [x] Animals bread
- [x] Player kills
- [x] Droppers opened
- [x] Hoppers opened
- [x] Dispensers opened
- [x] Chests opened
- [x] Furnaces opened
- [x] Crafting tables opened
- [x] Ender chests opened

**Comment by VaiTon** [comment]
Ender chests opened stat has been implemented in 4adbb3e0536738616a3cb2c3c4c84211f6ddd9bf
