### ISSUE TITLE
Completing entities in Glowstone

### ISSUE THREAD

**Issue by aramperes** [GlowstoneMC/Glowstone#396]
Entities are an essential component of Minecraft, and their functionality is not yet complete in Glowstone. This _Story_ was created to track remaining issues and missing functionality. I rewrote it to keep it up to date considering the recent changes in entity physics. The original content of this Story can be found [here](https://pastebin.com/zHPKRTec).

Anyone can participate in the completion of this issue, which will be a major turning point in the development and the possible use-cases for Glowstone as a Minecraft server alternative.

---

**Before getting started!** If you are unfamiliar with Glowstone, please remember that Glowstone is a complete _rewrite_ of the Minecraft vanilla server, aimed to be a better alternative to other software like Spigot. You are by no means allowed to push code to this repository based on Mojang's own platform (whether it be Forge, MCP, decompiled binaries, etc.) Doing so will cause in the rejection of your Pull Request. You are allowed to use other resources like the numerous wikis that exist on the Internet (Minecraft Wiki, wiki.vg, etc.) as well as trial-and-error.

---

Please see the following issues for each part of this story.

- [ ] [![Bountysource bounty badge](https://api.bountysource.com/badge/issue?issue_id=46548044)](https://www.bountysource.com/issues/46548044-396-entities-physics) [Physics (#501)](https://github.com/GlowstoneMC/Glowstone/issues/501)
- [ ] [![Bountysource bounty](https://api.bountysource.com/badge/issue?issue_id=46548045)](https://www.bountysource.com/issues/46548045-396-entities-ai) [AI (#502)](https://github.com/GlowstoneMC/Glowstone/issues/502)
- [ ] [![Bountysource bounty](https://api.bountysource.com/badge/issue?issue_id=46548046)](https://www.bountysource.com/issues/46548046-396-entities-pathfinding) [Pathfinding (#503)](https://github.com/GlowstoneMC/Glowstone/issues/503)
- [x] [![Bountysource bounty](https://api.bountysource.com/badge/issue?issue_id=46548049)](https://www.bountysource.com/issues/46548049-396-entities-implementation) [Implementation of individual entities (#504)](https://github.com/GlowstoneMC/Glowstone/issues/504)
- [ ] [![Bountysource bounty](https://api.bountysource.com/badge/issue?issue_id=46548051)](https://www.bountysource.com/issues/46548051-396-entities-projectiles) [Projectiles (#505)](https://github.com/GlowstoneMC/Glowstone/issues/505)

**Comment by gdude2002** [comment]
This story should be prioritised for April. I suggest breaking it down into smaller tasks and adding them to [the Intelligence Update board](https://github.com/GlowstoneMC/Glowstone/projects/3)

**Comment by gdude2002** [comment]
🔔 I've just posted a [$20 bounty](https://www.bountysource.com/issues/40545454-completing-entities-in-glowstone) for this ticket 🔔 

My biggest concern here is projectiles, but the entire story has a lot of important stuff on it. If people want to show their support for the importance of this ticket, they can feel free to add to the bounty!

**Comment by gdude2002** [comment]
🔔 Our sponsor, [Aternos](https://aternos.org/) has posted a [$50 bounty](https://www.bountysource.com/issues/40545454-70-completing-entities-in-glowstone) for this ticket 🔔 

This brings the total up to a whopping $70! Thanks, Aternos!

**Comment by aramperes** [comment]
Rewrote this issue to reflect the bounty, as well as updating what needs to be done (and removing what has already been completed).

**Comment by gdude2002** [comment]
Bountysource has helped us out by moving most of the bounties to the smaller tickets as users have been requesting. If you want to post a bounty, please post it to one of those instead.
