### ISSUE TITLE
Merge closed Glowstone pull requests

### ISSUE THREAD

**Issue by deathcap** [GlowstoneMC/Glowstone#55]
split off from https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/issues/6:
- Already added [#191](https://github.com/GlowstoneMC/Glowstone/pull/191) Difficulty setting in glowstone.yml
- Already added by entities-ecs, to be merged [#196](https://github.com/GlowstoneMC/Glowstone/pull/196) Gravity for entities
- [ ] [#211](https://github.com/GlowstoneMC/Glowstone/pull/211) Chest sounds and animations
- [ ] [#225](https://github.com/GlowstoneMC/Glowstone/pull/225) SIGTERM handling  
  Note: Changes are needed to quickly handle the SIGTERM, instead of doing the normal shutdown process.
- [x] [#226](https://github.com/GlowstoneMC/Glowstone/pull/226) Damage
- Functionality already added [#237](https://github.com/GlowstoneMC/Glowstone/pull/237) Inventory windows for all inventory blocks
- [x] [#242](https://github.com/GlowstoneMC/Glowstone/pull/242) Variable block sounds
- [ ] [#272](https://github.com/GlowstoneMC/Glowstone/pull/272) Prevent illegal placement
- Not valid [#274](https://github.com/GlowstoneMC/Glowstone/pull/274) getItemInHand()  
- Functionality already added [#286](https://github.com/GlowstoneMC/Glowstone/pull/286) Ore generation
- Already added by entities-ecs, to be merged [#282](https://github.com/GlowstoneMC/Glowstone/pull/282/) Entities  
- Functionality [#373](https://github.com/GlowstoneMC/Glowstone/pull/373) Player.isOnline()
- Functionality already added [#381](https://github.com/GlowstoneMC/Glowstone/pull/381) Redstone  
  Note: the main redstone PR has features the subsequent split ones do not. It would be preferable to add stuff in this PR that are not in the future PRs.
- Not valid [#386](https://github.com/GlowstoneMC/Glowstone/pull/386) Chat color
- [x] [#391](https://github.com/GlowstoneMC/Glowstone/pull/391) Network unit tests
- Functionality already added [#436](https://github.com/GlowstoneMC/Glowstone/pull/436) Basic Redstone support
- Functionality already added [#439](https://github.com/GlowstoneMC/Glowstone/pull/439) Redstone buttons and levers
- [ ] [#483](https://github.com/GlowstoneMC/Glowstone/pull/483) Configurable messages
- Not valid [#515](https://github.com/GlowstoneMC/Glowstone/pull/515) Space between > and command
- Functionality already added [#518](https://github.com/GlowstoneMC/Glowstone/pull/518) Fixes errors on join on a whitelist or ban
- Not valid [#587](https://github.com/GlowstoneMC/Glowstone/pull/587) Fix console check in headless environments  
- [ ] [#624](https://github.com/GlowstoneMC/Glowstone/pull/624) IO utils can load a world without a server
##

**Comment by gabizou** [comment]
BTW, the old code is up for grabs on the (almost completed) implementation of all living entities with [this pr](https://github.com/GlowstoneMC/Glowstone/pull/282).

**Comment by mastercoms** [comment]
I also saw your entities-ecs branch. Would that be better to merge over your main entities branch?

**Comment by gabizou** [comment]
> I also saw your entities-ecs branch. Would that be better to merge over your main entities branch?

We never got ECS to work, and even then, it's not a real ECS system. Ultimately, it's up to you guys, but I'd rather a quasi component system attached to entities to make the implementation work, and a bunch of systems to work with it.

**Comment by mastercoms** [comment]
Hmm ok. I guess I can merge the entities branch and then we can get ecs or a component system working later.
