### ISSUE TITLE
Merge open Glowstone Pull Requests

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone#6]
- [x] [#189](https://github.com/GlowstoneMC/Glowstone/pull/189) Switch to Netty ReadTimeoutHandler
- [x] [#358](https://github.com/GlowstoneMC/Glowstone/pull/358) Double chests
- [x] [#431](https://github.com/GlowstoneMC/Glowstone/pull/431) Random blocks tick
- [x] [#432](https://github.com/GlowstoneMC/Glowstone/pull/432) Bonemeal
- [x] [#444](https://github.com/GlowstoneMC/Glowstone/pull/444) Noteblocks and Jukeboxes
- [x] [#445](https://github.com/GlowstoneMC/Glowstone/pull/445) Dynamic Recipes
- [x] [#459](https://github.com/GlowstoneMC/Glowstone/pull/459) Scoreboards
- [x] [#473](https://github.com/GlowstoneMC/Glowstone/pull/473) Fix race conditions
- [x] [#477](https://github.com/GlowstoneMC/Glowstone/pull/477) Flower pots
- [x] [#484](https://github.com/GlowstoneMC/Glowstone/pull/484) Window click logic fix
- [x] [#501](https://github.com/GlowstoneMC/Glowstone/pull/501) Generate glowstone.yml defaults from the actual defaults
- [x] [#514](https://github.com/GlowstoneMC/Glowstone/pull/514) Item Frames
- [x] [#521](https://github.com/GlowstoneMC/Glowstone/pull/521) Fix player joining when they should be kicked
- [x] [#529](https://github.com/GlowstoneMC/Glowstone/pull/529) Titles API
- [x] [#533](https://github.com/GlowstoneMC/Glowstone/pull/533) Whitelist fixes
- [x] [#540](https://github.com/GlowstoneMC/Glowstone/pull/540) Fix wrong drops
- [x] [#541](https://github.com/GlowstoneMC/Glowstone/pull/541) Material attributes
- [x] [#553](https://github.com/GlowstoneMC/Glowstone/pull/553) Potion ItemMeta
- [x] [#564](https://github.com/GlowstoneMC/Glowstone/pull/564) Structures and structure saving
- [x] [#570](https://github.com/GlowstoneMC/Glowstone/pull/570) Basic LilyPad Support
- [x] [#572](https://github.com/GlowstoneMC/Glowstone/pull/572) Biome Decorators
- [x] [#591](https://github.com/GlowstoneMC/Glowstone/pull/591) Enchantments
- [x] [#597](https://github.com/GlowstoneMC/Glowstone/pull/597) biomegrid
- [x] [#599](https://github.com/GlowstoneMC/Glowstone/pull/599) Entities
- [x] [#607](https://github.com/GlowstoneMC/Glowstone/pull/607) Overworld worldgen
- [x] [#613](https://github.com/GlowstoneMC/Glowstone/pull/613) Configurable world height
- [x] [#618](https://github.com/GlowstoneMC/Glowstone/pull/618) Action message support
- [x] [#619](https://github.com/GlowstoneMC/Glowstone/pull/619) Bed interaction & sleeping
- [x] [#621](https://github.com/GlowstoneMC/Glowstone/pull/621) Fix getDrops() and breakNaturally()
- [x] [#623](https://github.com/GlowstoneMC/Glowstone/pull/623) Item attributes
- [x] [#631](https://github.com/GlowstoneMC/Glowstone/pull/631) Cauldrons
- [x] [#632](https://github.com/GlowstoneMC/Glowstone/pull/632) Block Suffocation
- [x] [#636](https://github.com/GlowstoneMC/Glowstone/pull/636) Water/lava physics
- [x] [#637](https://github.com/GlowstoneMC/Glowstone/pull/637) Lightning damage and ignites

And some closed PRs that may be useful
- (moved to https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/issues/55 -deathcap)

**Comment by mastercoms** [comment]
We should probably discuss each pull before we merge, especially the closed ones.

**Comment by deathcap** [comment]
Merged a few more which were straightforward or with only minor issues that can be fixed separately. The remaining open PRs (haven't looked at the closed PRs - but good catch digging those up, many do appear to be viable) mostly will be trickier to merge, requiring more changes. Some quick comments:

* 445 Dynamic Recipes: uses Glowkit Banner API (not available in Glowstone++), need to port to Spigot-Bukkit Banner API, but the PR does look like a good idea to me
* 459 Scoreboards - has an associated Glowkit API change; port to Spigot-Bukkit API
* 529 Implement Titles API - adds Glowkit API, not sure if Spigot has this API, may add
* 533 Rewrote whitelist code for PlayerProfile - probably the easiest of the open PRs to merge, haven't looked at it
* 564 Add some structures and their NBT storage - would love this. Merged all of @jimmikaelkael other open PRs (lots of cool new world gen), but they're tedious to merge because they all conflict with each other, presumably so they can be merged individually on Glowstone master (as this PR can). As the interdependent open PRs pile up they become harder and harder to merge and develop, I imagine that may be why the contributor asked https://forums.glowstone.net/t/is-the-project-development-frozen/166. @jimmikaelkael if you're here, would you be willing to help with Glowstone++, merging in your changes? I think I resolved all the conflicts properly, but you would know better..
* 570 Support LilyPad proxy information - seems useful, but haven't looked at it. Interestingly, Glowstone already supports BungeeCord, based on a Spigot patch: https://github.com/GlowstoneMC/Glowstone/issues/114
* 618 Add action message support - adds Glowkit API, does Spigot have anything similar?
* 627 Tool durability - has an unrelated commit "Fix Issue 622", otherwise probably ok
* 636 Water/lava physics - neat. but this PR is very new (3 days), is it stable?
* 637 Lightning damage and ignites - same as above (3 days old), though this one is a smaller change

**Comment by mastercoms** [comment]
So can you assign me some PRs to do so that we both don't end up doing the same work?

**Comment by TekkitCommando** [comment]
I might help with this as well if its ok, i have my a hosting company so unlimted free servers :P and I got a java background haha

**Comment by jimmikaelkael** [comment]
To be honest, while it seems to be a good move I'd prefer to continue the development in the Glowstone repo. I had some code for the nether generation almost ready and other stuff too but I prefer to wait if we can hear about @SpaceManiac. 

It should be trivial to merge my PRs provided you do it in the good order.

**Comment by TekkitCommando** [comment]
It's best to make sure that Glowstone is in good shape for usage by the community, I prefer Glowstone++'s ideas on how to do things, it should be a very awesome project when we have it all finished :P

**Comment by jimmikaelkael** [comment]
I'm currently enhancing "Lightning damage and ignites" PR so that it matches vanilla more closely.

**Comment by mastercoms** [comment]
Awesome! I'm working on Dynamic Recipes.

**Comment by jimmikaelkael** [comment]
Great! :)

**Comment by TekkitCommando** [comment]
Want me to do the whitelist fixes or titles API possibly?

**Comment by TekkitCommando** [comment]
Or just suggest one and I will work on it,I didn't look into why those 2 were skipped on the list but I'm sure it was for a good reason

**Comment by jimmikaelkael** [comment]
Hmmmm, I guess the title API requires some stuff to be merged in Glowkit. We should check too if spigot team has pulled something related to tile in their Bukkit fork.

**Comment by TekkitCommando** [comment]
ok will just try to do the whitelist code a maybe some others and just leave the Title API for now

**Comment by mastercoms** [comment]
Title API is not in Spigot, plugins have their own APIs that they use to display titles on Spigot servers.

Whitelist code is fine.

**Comment by TekkitCommando** [comment]
Ok well I will look into the pr's and decide which ones are priority

**Comment by jimmikaelkael** [comment]
Anyone currently handling PR #618 Action message support ?

**Comment by TekkitCommando** [comment]
Im not doing that one and @mastercoms isn't either i don't think but i am not 100% on that

**Comment by TekkitCommando** [comment]
I think i am gonna work on PR #627 if noone else has it or it hasn't already been implemented

**Comment by jimmikaelkael** [comment]
Ok.

**Comment by mastercoms** [comment]
Don't work on GlowstoneMC/#627. Dynamic Recipes includes that.

**Comment by mastercoms** [comment]
@jimmikaelkael Action message, titles, and tags should be done in 1 PR in my opinion, if someone will do it.

**Comment by jimmikaelkael** [comment]
Well I'll stay away of those PRs and concentrate on other aspects ;)

**Comment by TekkitCommando** [comment]
Ok

**Comment by deathcap** [comment]
Finished merging all open PRs, split off merging closed PRs into https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/issues/55
