### ISSUE TITLE
API Event Coverage

### ISSUE THREAD

**Issue by aramperes** [GlowstoneMC/Glowstone#922]
### *Disclaimer for new contributors*
Glowstone is an open-source project under the MIT license. In addition, we have a [Contributors License Agreement](https://glowstone.net/cla) which includes restrictions on the source of contributions (e.g. decompiled code from Mojang, Spigot, etc.). You will be asked to sign the CLA when submitting your first Pull Request.

### Task

As suggested by creatorfromhell, this is a to-do list of API events that are not partially or fully implemented in Glowstone, including a direct link to their documentation.

Events are an important aspect of our coverage of the Bukkit, Spigot, and Paper APIs.

In **bold** are events whose feature is implemented, but missing the event firing.

### Block Events

- [x] [BeaconEffectEvent](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/block/BeaconEffectEvent.html) (#1092)
- [x] [**BlockExplodeEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/block/BlockExplodeEvent.html) (#936)
- [ ] [BlockMultiPlaceEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/block/BlockMultiPlaceEvent.html)
- [x] [**BlockPhysicsEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/block/BlockPhysicsEvent.html)
- [X] [BlockPistonExtendEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/block/BlockPistonExtendEvent.html) (#1013)
- [x] [BlockPistonRetractEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/block/BlockPistonRetractEvent.html)
- [X] [**BlockRedstoneEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/block/BlockRedstoneEvent.html) (#1018)
- [x] [**CauldronLevelChangeEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/block/CauldronLevelChangeEvent.html) (2f16c28)
- [ ] [EntityBlockFormEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/block/EntityBlockFormEvent.html)

### Command Events
*Nothing here*

### Enchantment Events
*Nothing here*

### Entity Events
- [ ] [AreaEffectCloudApplyEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/AreaEffectCloudApplyEvent.html)
- [x] [**CreeperPowerEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/CreeperPowerEvent.html) (#925)
- [ ] [EndermanAttackPlayerEvent](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/entity/EndermanAttackPlayerEvent.html)
- [ ] [EndermanEscapeEvent](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/entity/EndermanEscapeEvent.html)
- [ ] [EnderDragonChangePhaseEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/EnderDragonChangePhaseEvent.html)
- [x] [**EntityAddToWorldEvent**](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/entity/EntityAddToWorldEvent.html) (#1063)
- [x] [**EntityAirChangeEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/EntityAirChangeEvent.html) (caa6e640c4c0ba05b8aa19f3efba539a2eb2df70)
- [ ] [EntityBreakDoorEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/EntityBreakDoorEvent.html)
- [ ] [EntityBreedEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/EntityBreedEvent.html)
- [ ] [EntityChangeBlockEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/EntityChangeBlockEvent.html) (*only partially implemented*)
- [ ] [EntityCombustByBlockEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/EntityCombustByBlockEvent.html)
- [ ] [EntityCombustByEntityEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/EntityCombustByEntityEvent.html)
- [ ] [**EntityDamageByBlockEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/EntityDamageByBlockEvent.html)
- [ ] [EntityPathfindEvent](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/entity/EntityPathfindEvent.html)
- [ ] [EntityPickupItemEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/EntityPickupItemEvent.html) (*only implemented for players*)
- [x] [**EntityRemoveFromWorldEvent**](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/entity/EntityRemoveFromWorldEvent.html) (#941)
- [x] [**EntityResurrectEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/EntityResurrectEvent.html)
- [x] [**EntityShootBowEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/EntityShootBowEvent.html) (#942)
- [x] [**EntityTameEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/EntityTameEvent.html) (b5ced2d4e4c6fb919ee0e793fc4cdf12b3d0a028)
- [ ] [EntityTargetEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/EntityTargetEvent.html)
- [ ] [EntityTargetLivingEntityEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/EntityTargetLivingEntityEvent.html)
- [x] [**EntityTeleportEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/EntityTeleportEvent.html) (#944)
- [ ] [EntityZapEvent](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/entity/EntityZapEvent.html)
- [ ] [ExperienceOrbMergeEvent](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/entity/ExperienceOrbMergeEvent.html)
- [x] [**ExpBottleEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/ExpBottleEvent.html) (#925)
- [ ] [HorseJumpEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/HorseJumpEvent.html)
- [x] [**ItemMergeEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/ItemMergeEvent.html) (#925)
- [ ] [LingeringPotionSplashEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/LingeringPotionSplashEvent.html)
- [ ] [PigZapEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/PigZapEvent.html)
- [ ] [PlayerNaturallySpawnCreaturesEvent](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/entity/PlayerNaturallySpawnCreaturesEvent.html)
- [x] [PotionSplashEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/PotionSplashEvent.html) (#945)
- [ ] [PreCreatureSpawnEvent](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/entity/PreCreatureSpawnEvent.html)
- [ ] [ProjectileCollideEvent](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/entity/ProjectileCollideEvent.html)
- [x] [**ProjectileHitEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/ProjectileHitEvent.html)
- [x] [**ProjectileLaunchEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/ProjectileLaunchEvent.html) (#933)
- [ ] [SheepRegrowWoolEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/SheepRegrowWoolEvent.html)
- [x] [SlimeSplitEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/SlimeSplitEvent.html) (#937)
- [ ] [SpawnerSpawnEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/SpawnerSpawnEvent.html)
- [ ] [VillagerAcquireTradeEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/VillagerAcquireTradeEvent.html)
- [ ] [VillagerReplenishTradeEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/VillagerReplenishTradeEvent.html)

### Hanging Entity Events
*Nothing here*

### Inventory Events
- [ ] [BrewEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/inventory/BrewEvent.html)
- [ ] [BrewingStandFuelEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/inventory/BrewingStandFuelEvent.html)
- [ ] [**FurnaceExtractEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/inventory/FurnaceExtractEvent.html)
- [ ] [**InventoryMoveItemEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/inventory/InventoryMoveItemEvent.html)
- [x] [**InventoryOpenEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/inventory/InventoryOpenEvent.html) (#938)
- [ ] [**InventoryPickupItemEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/inventory/InventoryPickupItemEvent.html)
- [ ] [**PrepareAnvilEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/inventory/PrepareAnvilEvent.html)
- [ ] [**PrepareItemCraftEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/inventory/PrepareItemCraftEvent.html)

### Player Events
- [ ] [**IllegalPacketEvent**](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/player/IllegalPacketEvent.html)
- [ ] [PlayerAdvancementCriterionGrantEvent](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/player/PlayerAdvancementCriterionGrantEvent.html)
- [ ] [**PlayerArmorChangeEvent**](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/player/PlayerArmorChangeEvent.html)
- [ ] [PlayerChangedMainHandEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/player/PlayerChangedMainHandEvent.html)
- [ ] [PlayerEditBookEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/player/PlayerEditBookEvent.html)
- [x] [**PlayerEggThrowEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/player/PlayerEggThrowEvent.html) (#932)
- [x] [**PlayerExpChangeEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/player/PlayerExpChangeEvent.html)
- [ ] [**PlayerHandshakeEvent**](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/player/PlayerHandshakeEvent.html)
- [x] [**PlayerInitialSpawnEvent**](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/player/PlayerInitialSpawnEvent.html) (#1051)
- [X] [**PlayerItemDamageEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/player/PlayerItemDamageEvent.html) (#1018)
- [ ] [PlayerItemMendEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/player/PlayerItemMendEvent.html)
- [ ] [**PlayerJumpEvent**](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/player/PlayerJumpEvent.html)
- [x] [**PlayerLevelChangeEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/player/PlayerLevelChangeEvent.html) (#983)
- [x] [PlayerLocaleChangeEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/player/PlayerLocaleChangeEvent.html) (#1011)
- [ ] [PlayerPickupArrowEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/player/PlayerPickupArrowEvent.html)
- [x] [PlayerPickupExperienceEvent](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/player/PlayerPickupExperienceEvent.html) (#1113)
- [ ] ~~[**PlayerPickupItemEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/player/PlayerPickupItemEvent.html)~~ (deprecated, replaced by `EntityPickupItemEvent`)
- [x] [**PlayerShearEntityEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/player/PlayerShearEntityEvent.html) (caa6e640c4c0ba05b8aa19f3efba539a2eb2df70)
- [x] [**PlayerStatisticIncrementEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/player/PlayerStatisticIncrementEvent.html) (#984)
- [x] [**PlayerSwapHandItemsEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/player/PlayerSwapHandItemsEvent.html) (#934)
- [ ] [PlayerTeleportEndGatewayEvent](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/player/PlayerTeleportEndGatewayEvent.html)
- [x] [**PlayerToggleFlightEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/player/PlayerToggleFlightEvent.html) (#931)
- [ ] [PlayerUseUnknownEntityEvent](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/player/PlayerUseUnknownEntityEvent.html)

### Profile Events
- [ ] [**FillProfileEvent**](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/profile/FillProfileEvent.html)
- [ ] [**LookupProfileEvent**](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/profile/LookupProfileEvent.html)
- [ ] [**PreFillProfileEvent**](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/profile/PreFillProfileEvent.html)
- [ ] [**PreLookupProfileEvent**](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/profile/PreLookupProfileEvent.html)
- [x] [**ProfileWhitelistVerifyEvent**](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/profile/ProfileWhitelistVerifyEvent.html) (4c7e8c03021ddaf380314226a24efa21f3926165)

### Server Events
- [ ] [**AsyncTabCompleteEvent**](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/server/AsyncTabCompleteEvent.html)
- [x] [**BroadcastMessageEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/server/BroadcastMessageEvent.html)
- [ ] [MapInitializeEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/server/MapInitializeEvent.html)
- [ ] [ServerExceptionEvent](https://papermc.io/javadocs/paper/1.12/com/destroystokyo/paper/event/server/ServerExceptionEvent.html)
- [ ] [ServiceRegisterEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/server/ServiceRegisterEvent.html)
- [ ] [ServiceUnregisterEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/server/ServiceUnregisterEvent.html)

### Vehicle Events
- [ ] [VehicleBlockCollisionEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/vehicle/VehicleBlockCollisionEvent.html)
- [x] [**VehicleCreateEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/vehicle/VehicleCreateEvent.html)
- [x] [**VehicleEnterEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/vehicle/VehicleEnterEvent.html) (#939)
- [X] [**VehicleExitEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/vehicle/VehicleExitEvent.html) (#1018)
- [ ] [VehicleUpdateEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/vehicle/VehicleUpdateEvent.html)

### Weather Events
*Nothing here*

### World Events
- [ ] [**PortalCreateEvent**](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/world/PortalCreateEvent.html)

**Comment by VaiTon** [comment]
`EntityShootBowEvent` is implemented [here ](https://github.com/GlowstoneMC/Glowstone/blob/dev/src/main/java/net/glowstone/block/itemtype/ItemBow.java#L85)

**Comment by heisluft** [comment]
I implemented PlayerLocaleChangeEvent in #1011

**Comment by aramperes** [comment]
@VaiTon I see that a few commits in your fork mentioned this issue. Do you plan on PR-ing these changes?

**Comment by jhg023** [comment]
All of the links to the respective event documentation seem to be dead 👻

**Comment by SHADOWDANCH** [comment]
`BlockPistonRetractEvent` is firing [here](https://github.com/GlowstoneMC/Glowstone/blob/dev/src/main/java/net/glowstone/block/blocktype/BlockPiston.java#L168)
`BroadcastMessageEvent` is firing [here](https://github.com/GlowstoneMC/Glowstone/blob/dev/src/main/java/net/glowstone/GlowServer.java#L2131)
`ProjectileHitEvent` is firing [here](https://github.com/GlowstoneMC/Glowstone/blob/dev/src/main/java/net/glowstone/entity/GlowEntity.java#L1034)
`PlayerExpChangeEvent` is firing [here](https://github.com/GlowstoneMC/Glowstone/blob/dev/src/main/java/net/glowstone/entity/GlowPlayer.java#L1721)
`VehicleCreateEvent` is firing [here](https://github.com/GlowstoneMC/Glowstone/blob/dev/src/main/java/net/glowstone/entity/GlowVehicle.java#L16)

**Comment by SHADOWDANCH** [comment]
`BlockPhysicsEvent` is firing [here](https://github.com/GlowstoneMC/Glowstone/blob/dev/src/main/java/net/glowstone/block/blocktype/BlockType.java#L319)

**Comment by aramperes** [comment]
I updated the links to use the Paper 1.12 docs, so they should no longer be dead.

**Comment by JoelLau** [comment]
I'm decent at Java, admire minecraft (have the game), but don't play much. Would anybody be willing to give me guide me as I make my first pull requests here ?

**Comment by VaiTon** [comment]
`BeaconEffectEvent` has been implemented in c4c59a7ebd263cf220a88382e882073bca7d267d.
